<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Tino Hager</Authors>
    <Company>nager.at</Company>
    <Description>Read frames from a rtsp video stream or from a video file</Description>
    
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    
    <LangVersion>12.0</LangVersion>
    <IncludeSymbols>true</IncludeSymbols>
    
    <Nullable>enable</Nullable>
    
    <PackageIcon>camera.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <!--<PackageReadmeFile>README.md</PackageReadmeFile>-->
    <!--<PackageReleaseNotes>A changelog is available at https://github.com/nager/Nager.VideoStream/releases</PackageReleaseNotes>-->
    <PackageProjectUrl>https://github.com/nager/Nager.VideoStream</PackageProjectUrl>
    <PackageTags>video;stream;rtsp;frame;camera</PackageTags>
    
    <RepositoryUrl>https://github.com/nager/Nager.VideoStream</RepositoryUrl>
    
    <TargetFrameworks>net481;netstandard2.0;net10.0</TargetFrameworks>
    
    <!-- Version is automatically replaced by build process -->
    <Version>1.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\doc\icons\camera.png">
      <Pack>true</Pack>
      <Visible>false</Visible>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  
</Project>
